FROM node:lts-alpine
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --silent

# Copy source code
COPY . .

# Backend port
EXPOSE 3000

# Start command
CMD ["node", "src/index.js"]
