FROM node:lts-alpine AS frontend-build
WORKDIR /app
COPY package*.json ./
RUN npm install --silent
COPY . .
RUN npm run build -- --configuration=production --base-href=/

FROM nginx:alpine
# Copy custom nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# CORRECTED PATH: Angular 17+ outputs to dist/[project-name]/browser
COPY --from=frontend-build /app/dist/tsr/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
