FROM node:lts-alpine
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --silent

# Copy all source code
COPY . .

# Backend port
EXPOSE 3000

# Command to start your backend
CMD ["node", "src/index.js"]
